"""Generated by ois_textcheck.py -- spelling/grammar fixes for apply_data_fixes.py.

Same shape as apply_data_fixes.FIXES: file -> [(expected_count, old, new)].
Each snippet is verified against your own game files before it is applied."""

TEXT_FIXES = {
    'amp_amalynpelle2.txt': [
        (1, 'anther non-person. Like me.', 'another non-person. Like me.'),
    ],
    'aof_jacksonfarlane.txt': [
        (1, 'that way beacuse the words are', 'that way because the words are'),
    ],
    'asv_jacquiengels.txt': [
        (1, 'text=Fascinatng, but can we', 'text=Fascinating, but can we'),
        (1, 'all the excietment is about myself.', 'all the excitement is about myself.'),
    ],
    'asv_jacquiengels2.txt': [
        (1, 'back here, thankyou. Any hurdles', 'back here, thank you. Any hurdles'),
    ],
    'bdb_hugodebeersemail1.txt': [
        (1, 'an unrealiable captain again.^^dB.^', 'an unreliable captain again.^^dB.^'),
    ],
    'bds_johnjamessalomon11.txt': [
        (1, 'at the Langrange Animal Habitat', 'at the Lagrange Animal Habitat'),
    ],
    'bds_johnjamessalomonemail1.txt': [
        (2, 'someone. I reliase my situation', 'someone. I realise my situation'),
    ],
    'bnb_makroberts2.txt': [
        (1, 'device is a bit of a trademarks of these vile Svobudra.', 'device is a bit of a trademark of these vile Svobudra.'),
    ],
    'bug_caseycroma2.txt': [
        (1, "text=Why didn'y you tell me", "text=Why didn't you tell me"),
    ],
    'bug_caseycromaemail1.txt': [
        (1, 'promised.^^Furhter, I made a connection', 'promised.^^Further, I made a connection'),
    ],
    'ch1_beaconemails.txt': [
        (1, 'his place,^Now the the planet hears the blast.^^As', 'his place,^Now the planet hears the blast.^^As'),
    ],
    'ch1_nigelbennett.txt': [
        (1, "text=When she get's my message.", 'text=When she gets my message.'),
        (1, 'those who weild the guns.', 'those who wield the guns.'),
    ],
    'ch2_michaelrangsikitpho.txt': [
        (1, 'but cental to intercept', 'but central to intercept'),
    ],
    'convoyattack2.txt': [
        (1, 'Deeshue.^^Our enemies intelligence outclasses our', "Deeshue.^^Our enemy's intelligence outclasses our"),
    ],
    'cp2_capabilitymiltonemail1.txt': [
        (1, 'to jump fpr five days now.', 'to jump for five days now.'),
    ],
    'cpb_naividaziz.txt': [
        (1, 'text=Absoutely am! So what', 'text=Absolutely am! So what'),
    ],
    'd38_samkasrils.txt': [
        (1, 'position to use this warheads to build defensive', 'position to use these warheads to build defensive'),
        (1, 'on any staiton. You know about', 'on any station. You know about'),
        (1, "W on them. The're a trading terminal we use for less", "W on them. There's a trading terminal we use for less"),
        (1, 'for these wareheads will be Zhou', 'for these warheads will be Zhou'),
    ],
    'dac_emiliafalzon.txt': [
        (1, 'Cansa is unaccaptable. No one must', 'Cansa is unacceptable. No one must'),
        (1, 'of your jouney in Cansa. Best', 'of your journey in Cansa. Best'),
    ],
    'dac_tepurangata.txt': [
        (1, 'a real nuciance. Anyone who', 'a real nuisance. Anyone who'),
        (1, 'however, is that the it mirrors old Earth imperialism', 'however, is that it mirrors old Earth imperialism'),
        (1, "but I'll put a in good word for you. I'm", "but I'll put in a good word for you. I'm"),
    ],
    'dbc_andreikovac.txt': [
        (1, "Diwali. It's contents are need-to-know,", 'Diwali. Its contents are need-to-know,'),
        (1, 'this job, it will lucrative for you. Are you certain?', 'this job, it will be lucrative for you. Are you certain?'),
    ],
    'dbc_andreikovacemail5.txt': [
        (1, "simpleton. I would've have guessed you'd already", "simpleton. I would have guessed you'd already"),
    ],
    'dbc_stephaniebeatrice.txt': [
        (1, "and I don't ahve it. But listen,", "and I don't have it. But listen,"),
    ],
    'ddf_nickfourier.txt': [
        (1, 'ship was a haemmorhaging wound, so we', 'ship was a haemorrhaging wound, so we'),
    ],
    'ddf_nickfourier3.txt': [
        (1, "they were harlmess? They didn't", "they were harmless? They didn't"),
    ],
    'ddf_nickfourieremail.txt': [
        (1, 'subject=coorindates', 'subject=coordinates'),
    ],
    'ddu_kestajones.txt': [
        (1, 'to go and find some where someone left some than', 'to go and find somewhere someone left some than'),
    ],
    'ddu_kestajonesemail1.txt': [
        (1, "sure isn't glamourous but it pays", "sure isn't glamorous but it pays"),
    ],
    'ddu_kestajonesemail2.txt': [
        (1, 'in them or if their full. Should be worth', "in them or if they're full. Should be worth"),
    ],
    'dkc_daphnekolleremail1.txt': [
        (1, "though - it's is no longer being detected.", 'though - it is no longer being detected.'),
    ],
    'dsy_drclarkemathisonemail1.txt': [
        (1, '^ ^If this has peaked your interest at all, meet', '^ ^If this has piqued your interest at all, meet'),
    ],
    'dsy_drclarkemathisonemail2.txt': [
        (1, 'body=Dear catpain,^^I want you', 'body=Dear captain,^^I want you'),
    ],
    'dsy_drmathison.txt': [
        (1, "we'd have beeen gifted a little", "we'd have been gifted a little"),
    ],
    'dsy_drmathison2.txt': [
        (1, "but I doubt they'll answered, so let's just", "but I doubt they'll answer, so let's just"),
    ],
    'dsy_terrypolaris3.txt': [
        (1, 'text=Lieutennants #stand_fingerwag', 'text=Lieutenants #stand_fingerwag'),
        (1, "human, you undertand. She's a clone,", "human, you understand. She's a clone,"),
    ],
    'dup_ulencefederationemail1.txt': [
        (2, 'any and all dilligence in any matters', 'any and all diligence in any matters'),
    ],
    'efe_drazaterroiremail1.txt': [
        (1, "Terroir.^^I'll back back very shortly!", "Terroir.^^I'll be back very shortly!"),
    ],
    'epg_lescanard.txt': [
        (1, "out of Caruthers' Circle. Three", "out of Carruthers' Circle. Three"),
    ],
    'factions.txt': [
        (1, 'of ships licesned to work for', 'of ships licensed to work for'),
        (1, 'of our work invovles transporting', 'of our work involves transporting'),
        (1, 'will be the tranport of various goods', 'will be the transport of various goods'),
        (1, 'elsewhere throughtout Apollo.^^We', 'elsewhere throughout Apollo.^^We'),
        (1, 'that any failured on UBP assignments', 'that any failure on UBP assignments'),
        (1, 'logstics company for', 'logistics company for'),
        (1, 'unlock more challening routes with', 'unlock more challenging routes with'),
        (1, 'the cluser from its factories', 'the cluster from its factories'),
    ],
    'fbl_fanbrigolabre.txt': [
        (1, "Right. I gues that's the kernel", "Right. I guess that's the kernel"),
    ],
    'fws_docgojic.txt': [
        (1, '- mass dormatories and mess halls', '- mass dormitories and mess halls'),
        (1, "but really we'e on our own up", "but really we're on our own up"),
    ],
    'fws_rocket.txt': [
        (1, 'gives me everythig I need.', 'gives me everything I need.'),
        (1, 'system extravagences!', 'system extravagances!'),
    ],
    'goods.txt': [
        (1, 'priarily.', 'primarily.'),
        (1, 'other rare crystaline structures highly', 'other rare crystalline structures highly'),
    ],
    'hlm_herschelli.txt': [
        (1, 'to our extracirricular research. We', 'to our extracurricular research. We'),
    ],
    'hlm_herschelli2.txt': [
        (1, 'Meier U. An ususual gravitational', 'Meier U. An unusual gravitational'),
    ],
    'hme_hart4.txt': [
        (1, 'can maessage the hacking', 'can message the hacking'),
    ],
    'hme_hart5.txt': [
        (1, 'habitation sectino was sent to', 'habitation section was sent to'),
    ],
    'hme_hartemail1.txt': [
        (1, "I'm sorry I had flee your vessel without saying", "I'm sorry I had to flee your vessel without saying"),
    ],
    'info_asteroids.txt': [
        (1, 'can be spoted on your Nav', 'can be spotted on your Nav'),
    ],
    'info_damage.txt': [
        (1, 'have vital moduels on your port', 'have vital modules on your port'),
        (1, 'hull is exposed from from the aft of your ship,', 'hull is exposed from the aft of your ship,'),
    ],
    'info_dockingandundocking.txt': [
        (1, 'with using your ships autopilot system. You', "with using your ship's autopilot system. You"),
    ],
    'info_engineering.txt': [
        (1, '* Emmissions        - Emissions', '* Emissions        - Emissions'),
    ],
    'info_grapplingarms.txt': [
        (1, 'If have Grappling Arm, you can select', 'If you have a Grappling Arm, you can select'),
        (1, "ship which you've spend several hundred credits", "ship which you've spent several hundred credits"),
    ],
    'info_magellanempire.txt': [
        (1, 'but also constols various colonies', 'but also controls various colonies'),
    ],
    'info_mooring.txt': [
        (1, 'In order to retreive cargo, your', 'In order to retrieve cargo, your'),
    ],
    'info_navmap.txt': [
        (1, 'your ship whcih indicates the', 'your ship which indicates the'),
    ],
    'info_parssusunion.txt': [
        (1, 'It has one of two major capital shipyard in the Apollo', 'It has one of two major capital shipyards in the Apollo'),
    ],
    'info_pda.txt': [
        (1, 'come out whenver you are talking', 'come out whenever you are talking'),
    ],
    'info_powerbars.txt': [
        (1, 'two large verticel bars on your', 'two large vertical bars on your'),
    ],
    'info_powerroom.txt': [
        (1, 'not it is inlcuded in the EmCon', 'not it is included in the EmCon'),
    ],
    'info_rcs.txt': [
        (1, 'emissions visibilty, so ideally', 'emissions visibility, so ideally'),
    ],
    'info_ulencefederation.txt': [
        (1, 'the remians of EarthGate.', 'the remains of EarthGate.'),
    ],
    'int_lesliegarbut.txt': [
        (1, "are, yes. Your gonna keep on spinnin' and", "are, yes. You're gonna keep on spinnin' and"),
        (1, "you, yes. Your gonna keep on spinnin' and", "you, yes. You're gonna keep on spinnin' and"),
    ],
    'int_notes.txt': [
        (1, 'proceed thorugh the airlock,', 'proceed through the airlock,'),
    ],
    'jfs_angelareddy.txt': [
        (1, 'let it be publically known, not until', 'let it be publicly known, not until'),
    ],
    'jfs_angelareddy4.txt': [
        (1, "legend, I couldn't have do this without you.", "legend, I couldn't have done this without you."),
    ],
    'lfw_lesterfward.txt': [
        (1, "finish my affiars here and we'll", "finish my affairs here and we'll"),
        (1, "but end up insuting them! Why can't", "but end up insulting them! Why can't"),
        (1, "text=I'm afriad it's just a", "text=I'm afraid it's just a"),
    ],
    'lfw_lesterfward4.txt': [
        (1, 'look it up if you every get there.', 'look it up if you ever get there.'),
    ],
    'loj_angelareddy.txt': [
        (1, 'of choice. I need see what he has to say.', 'of choice. I need to see what he has to say.'),
    ],
    'loj_angelareddy3.txt': [
        (1, 'ship and wait for your to get back.', 'ship and wait for you to get back.'),
    ],
    'loj_harryvuong.txt': [
        (1, 'Angela to come and and meet with me I will', 'Angela to come and meet with me I will'),
    ],
    'loj_harryvuong2.txt': [
        (1, 'Angela in exhange for the information', 'Angela in exchange for the information'),
    ],
    'lwf_avelinadembo.txt': [
        (1, 'have this shiping manifest. We', 'have this shipping manifest. We'),
        (1, "everything, it's importance is only just being", 'everything, its importance is only just being'),
    ],
    'lwf_avelinademboemail1.txt': [
        (1, 'See waht else I can find', 'See what else I can find'),
    ],
    'lyot_trading.txt': [
        (1, '4 down for maintainance.', '4 down for maintenance.'),
    ],
    'mhn_mahuikangata.txt': [
        (1, 'big, unweildy actually. I', 'big, unwieldy actually. I'),
        (1, 'trying, but its too little too late if you ask me.', "trying, but it's too little too late if you ask me."),
        (1, 'to see you weilding a hand cannon.', 'to see you wielding a hand cannon.'),
        (1, 'I hope for your sake its not on your ship', "I hope for your sake it's not on your ship"),
    ],
    'mhn_mahuikangataemail1.txt': [
        (2, 'system that priviliges the few over', 'system that privileges the few over'),
    ],
    'mjb_majalindqvist.txt': [
        (1, 'to justify extravagences like this?', 'to justify extravagances like this?'),
        (1, 'people were sketpical that EarthGate', 'people were sceptical that EarthGate'),
    ],
    'modules_arms.txt': [
        (4, 'the safe retreival of cargo from', 'the safe retrieval of cargo from'),
        (4, 'scavanging!^^Your friendly', 'scavenging!^^Your friendly'),
    ],
    'modules_npc.txt': [
        (1, 'battery exlusively used in weapons.', 'battery exclusively used in weapons.'),
    ],
    'msa_marisafranck.txt': [
        (1, "you're fee. Thanks for", 'your fee. Thanks for'),
    ],
    'msa_marisafranckemail1.txt': [
        (1, "Fly to Casnsa. You're looking", "Fly to Cansa. You're looking"),
        (1, 'afraid we shant be paying you', "afraid we shan't be paying you"),
    ],
    'msa_marisafranckemail2.txt': [
        (1, 'for your assitance.^^Regards,^^Marisa', 'for your assistance.^^Regards,^^Marisa'),
    ],
    'mwg_dannydurst.txt': [
        (1, 'troubles? Gerenous, I know, but', 'troubles? Generous, I know, but'),
    ],
    'mwg_dannydurstemail1.txt': [
        (1, 'subject=Paasenger Transport -', 'subject=Passenger Transport -'),
    ],
    'news_10000slavesreturntodiwali.txt': [
        (1, 'of the Cansn', 'of the Cansa'),
        (1, 'disapora," said a spokesperson', 'diaspora," said a spokesperson'),
        (1, 'stretched beyons its means, is', 'stretched beyond its means, is'),
    ],
    'news_accidentonspacefiringrange.txt': [
        (1, 'Accoridng to a source', 'According to a source'),
    ],
    'news_additionalvesselstostopcarrutheransentergingalileo.txt': [
        (1, 'immigration ministr Pavel Anta.', 'immigration minister Pavel Anta.'),
    ],
    'news_admiralswitchinmaru.txt': [
        (1, 'much more foreceful in the region.', 'much more forceful in the region.'),
    ],
    'news_aeahasnoauthorityanymoresaysperera.txt': [
        (1, 'from a non-existant Apollo-Earth', 'from a non-existent Apollo-Earth'),
        (1, '"Snice the Wolf Trade', '"Since the Wolf Trade'),
    ],
    'news_alarmingpiratepresencedetected.txt': [
        (1, 'been living entirly in EmCon mode', 'been living entirely in EmCon mode'),
    ],
    'news_areleonpurchasesindiwaliupfortheaeatreatment.txt': [
        (1, 'Rubmlings from Lagrange', 'Rumblings from Lagrange'),
    ],
    'news_arepeoplebeingpaidtobefauxviolentprotesters.txt': [
        (1, 'groups to pose as a disgruntled workers and become violent', 'groups to pose as disgruntled workers and become violent'),
    ],
    'news_atlasstarcaughthaulinggoodsfromdevassstar.txt': [
        (1, 'in the Empre, has been caught', 'in the Empire, has been caught'),
    ],
    'news_attackersofproudstillatlarge.txt': [
        (1, 'of Cansa, so its hardly a surprise given our long', "of Cansa, so it's hardly a surprise given our long"),
        (1, 'have been termporarily suspended from', 'have been temporarily suspended from'),
    ],
    'news_attemptonthegovernorslife.txt': [
        (1, 'from condifential informants that', 'from confidential informants that'),
    ],
    'news_bednarskideployedtomurrindal.txt': [
        (1, "The move way well see Bednarski's", "The move may well see Bednarski's"),
    ],
    'news_bednarskiimpressesataurorashipyard.txt': [
        (1, 'Mines, Genearl Felicia Bednarski', 'Mines, General Felicia Bednarski'),
    ],
    'news_bednarskiinvadesparssus.txt': [
        (1, 'the Parssus sytem with her entire', 'the Parssus system with her entire'),
    ],
    'news_bednarskisaysparssusrepwillnotbeharmed.txt': [
        (1, 'new General Secreatary of the Parssus', 'new General Secretary of the Parssus'),
    ],
    'news_boldanticapitalistmovesmadebymiawilliams.txt': [
        (1, 'Dalca to institude strong anti-capitalist', 'Dalca to institute strong anti-capitalist'),
    ],
    'news_boronovakoutlineshisconservativeplatform.txt': [
        (1, 'and fiscal irresonsibility of the Korpal', 'and fiscal irresponsibility of the Korpal'),
    ],
    'news_bothempirescautionnewgalileanpresident.txt': [
        (1, 'appointed socailist leader had this', 'appointed socialist leader had this'),
    ],
    'news_bronletter.txt': [
        (1, 'system that priviliges the few over', 'system that privileges the few over'),
    ],
    'news_cannibaltried.txt': [
        (1, "Okpik condemnded the man's action,", "Okpik condemned the man's action,"),
        (1, 'face the detah penalty for', 'face the death penalty for'),
    ],
    'news_cassandrainvestmentstobepartiallyprivatised.txt': [
        (1, 'federal invesemtnt bank within', 'federal investment bank within'),
    ],
    'news_cballapollonianchampionshipskickoff.txt': [
        (1, 'face off agains the Tegan Brutes', 'face off against the Tegan Brutes'),
    ],
    'news_chaosattsemosfuneral.txt': [
        (1, 'Magellan atendees.', 'Magellan attendees.'),
    ],
    'news_co2scrubbersmalfunctioningonadari.txt': [
        (1, '"Maintainance of life support', '"Maintenance of life support'),
    ],
    'news_conditionsondourosatworstpointinyears.txt': [
        (1, 'and raido silence on their', 'and radio silence on their'),
    ],
    'news_controversialnewlawbanschildrenfromcertainmakeupandclothes.txt': [
        (1, 'them! It send a completely wrong message', 'them! It sends a completely wrong message'),
    ],
    'news_correausesaeahearingsagainstdetractor.txt': [
        (1, 'made a statment today saying', 'made a statement today saying'),
        (1, 'of food tarrifs being imposed', 'of food tariffs being imposed'),
    ],
    'news_crackdownannouncedafterassassinationattempt.txt': [
        (1, 'terrorists responsibile.', 'terrorists responsible.'),
        (1, 'or miltiary personnel from', 'or military personnel from'),
        (1, 'leaving the suface of Douros. With', 'leaving the surface of Douros. With'),
    ],
    'news_cruiselinerorsextourism.txt': [
        (1, 'in the cental systems have', 'in the central systems have'),
    ],
    'news_dalcafacesthemusicovercansa.txt': [
        (1, 'bring as prood that a larger', 'bring as proof that a larger'),
    ],
    'news_delacroixandherreradeclaresideswitherikavang.txt': [
        (1, 'a public statment of intent to', 'a public statement of intent to'),
    ],
    'news_delegatereturnstoparssus.txt': [
        (1, 'have been exected, Kleg is expected', 'have been executed, Kleg is expected'),
    ],
    'news_didokpikcreateaprivatepoliceforceindiwali.txt': [
        (1, "Herrera's lieutennants.", "Herrera's lieutenants."),
    ],
    'news_dierdremacniallisthenewpresidentofthegalileancommand.txt': [
        (1, 'past. Our administartion will be clean,', 'past. Our administration will be clean,'),
    ],
    'news_documentaryshineslightonteganlegalsystem.txt': [
        (1, 'being inadmissable or tainted.', 'being inadmissible or tainted.'),
    ],
    'news_dysonstrippossible.txt': [
        (1, 'on Lagrange have release a paper theorising that', 'on Lagrange have released a paper theorising that'),
    ],
    'news_earthfoodsaccusedofpricegouging.txt': [
        (1, 'Earthfoods weilds is currently', 'Earthfoods wields is currently'),
    ],
    'news_earthgateshockatresumedaeahearings.txt': [
        (1, 'with an intersellar consensus that', 'with an interstellar consensus that'),
    ],
    'news_emergencyattheleonmagellanblockade.txt': [
        (1, 'THe ship drifted right into the', 'The ship drifted right into the'),
    ],
    'news_emprieapologisestoshockvictims.txt': [
        (1, 'and indisciminately punishes poor', 'and indiscriminately punishes poor'),
    ],
    'news_explosionrockscoxsbazaar.txt': [
        (1, 'with the produciton of or intent', 'with the production of or intent'),
        (1, 'nominally subsribing to Empire law,', 'nominally subscribing to Empire law,'),
    ],
    'news_explosiveladenvesselfoundinparssus.txt': [
        (1, 'took the opportunit to make a statement:', 'took the opportunity to make a statement:'),
        (1, 'them out whenver we can."', 'them out whenever we can."'),
    ],
    'news_explosiveweaponsbanintega.txt': [
        (1, 'to note the availablility of countermeasures,', 'to note the availability of countermeasures,'),
    ],
    'news_fearsovernewsexuallytransmitteddiseaseonoyaaldoumin.txt': [
        (1, "any sexual actvity 'involving physical", "any sexual activity 'involving physical"),
    ],
    'news_fertilitynewsrecalledforpoliticalreasons.txt': [
        (1, 'that low fertiliy rates on Rossi', 'that low fertility rates on Rossi'),
    ],
    'news_firstaeahearingsindecadesmoveahead.txt': [
        (1, "Empire's tarrifs on foodstuffs", "Empire's tariffs on foodstuffs"),
        (1, 'for interstallar trade and meta-industry', 'for interstellar trade and meta-industry'),
    ],
    'news_fleetfromdevassstargivesaid.txt': [
        (1, 'General Secreatary Felicia Bednarski', 'General Secretary Felicia Bednarski'),
    ],
    'news_foodshortagesalleviatedinthetwosisters.txt': [
        (1, 'things work thorugh this difficult', 'things work through this difficult'),
    ],
    'news_francishaldarinterviewpartone.txt': [
        (1, "life many citizen can't imagine life", "life many citizens can't imagine life"),
    ],
    'news_francishaldarinterviewparttwo.txt': [
        (1, "in. One where we're are all on-board and", "in. One where we're all on-board and"),
        (1, 'has been some been some comment in the local', 'has been some comment in the local'),
    ],
    'news_freebohringersdiseasevaccineforallofapollo.txt': [
        (1, 'cluster to synthetsise their own at', 'cluster to synthesise their own at'),
    ],
    'news_fuelcellstartsconstructionoutsidegalileo.txt': [
        (1, 'today, as contruction formally begins', 'today, as construction formally begins'),
        (1, 'popular senitment appears to be', 'popular sentiment appears to be'),
        (1, 'here, as Galiliean people rally', 'here, as Galilean people rally'),
    ],
    'news_fullinterimcabinetrevealedformacniallgovernment.txt': [
        (2, 'Cabinet Revaeled for MacNiall', 'Cabinet Revealed for MacNiall'),
    ],
    'news_galaxyannouncespartnershipwitharakaki.txt': [
        (1, 'rest of the cluser has been able', 'rest of the cluster has been able'),
    ],
    'news_galileaneconomyunstablestudy.txt': [
        (1, 'has taken a hollistic approach, considering', 'has taken a holistic approach, considering'),
        (1, 'colony maintainance costs over several', 'colony maintenance costs over several'),
    ],
    'news_galileocomestosarnisaid.txt': [
        (1, 'Reagrdless, this influx', 'Regardless, this influx'),
    ],
    'news_gasminesindevassstar.txt': [
        (1, 'inside a cacophany of dangerous', 'inside a cacophony of dangerous'),
        (1, 'of the veractiy of these claims', 'of the veracity of these claims'),
    ],
    'news_giveusbackkadirisaycansans.txt': [
        (1, 'petition as he has ever year.', 'petition as he has every year.'),
        (1, 'play into a heirarchy imposed upon', 'play into a hierarchy imposed upon'),
    ],
    'news_gruesomemurderonateakanada.txt': [
        (1, 'found dead, disembowled and strung up', 'found dead, disembowelled and strung up'),
    ],
    'news_herrerapledgestoprotectdadraandsarni.txt': [
        (1, 'but his motived are questioned', 'but his motives are questioned'),
    ],
    'news_humanlabgrownmeatbeingeateninmaru.txt': [
        (1, 'authorities preocuppied with policing', 'authorities preoccupied with policing'),
    ],
    'news_iamincommandoftheparssusuniondeclaredbednarski.txt': [
        (1, 'be the purcursor to a coup inside', 'be the precursor to a coup inside'),
    ],
    'news_ilongedfordeathbeforeoedipusdid.txt': [
        (1, 'quality of thier production now', 'quality of their production now'),
    ],
    'news_indefenceofpublicworks.txt': [
        (1, 'use as a politcal wedge. In both', 'use as a political wedge. In both'),
        (1, 'people are artifically inflating the', 'people are artificially inflating the'),
    ],
    'news_inflatablehousingconfusion.txt': [
        (1, 'or semi-permaneny housing, so', 'or semi-permanently housing, so'),
    ],
    'news_issandinvolvedindiwalismisfortune.txt': [
        (1, 'Sand is scaringly popular, and', 'Sand is scarily popular, and'),
    ],
    'news_janskycolonylocationstilluncertain.txt': [
        (1, 'clear that Galielans in both Galileo', 'clear that Galileans in both Galileo'),
        (1, 'the idea abbhorent.', 'the idea abhorrent.'),
    ],
    'news_janskyconstructiondealangerstheempires.txt': [
        (1, "ensure poor realtions don't jeopardise", "ensure poor relations don't jeopardise"),
    ],
    'news_janskydeathtollrising.txt': [
        (1, 'of a amssive explosion on', 'of a massive explosion on'),
    ],
    'news_janskyreportconcludes.txt': [
        (1, 'gas cannisters found throughout', 'gas canisters found throughout'),
        (1, 'of the gas cannisters their team has', 'of the gas canisters their team has'),
    ],
    'news_leonaerospacecracksdown.txt': [
        (1, 'having siezed at least 500kg', 'having seized at least 500kg'),
        (1, 'It has also siezed property from', 'It has also seized property from'),
        (1, 'a number of siezed vessels will', 'a number of seized vessels will'),
    ],
    'news_leoncorporationsmakemassivelandgrabindiwali.txt': [
        (1, 'A Leon diplimatic delegate to', 'A Leon diplomatic delegate to'),
        (1, 'that the puchases could be taken', 'that the purchases could be taken'),
    ],
    'news_leonrepresentativetakesswingsatmagella.txt': [
        (1, 'defend its tarrifs.', 'defend its tariffs.'),
        (1, 'to impose tarrifs on the Magellan', 'to impose tariffs on the Magellan'),
    ],
    'news_lifereturnstornormalintheunion.txt': [
        (1, 'is finally beginnign to return to', 'is finally beginning to return to'),
    ],
    'news_lostmilitaryshipsparkscontroversy.txt': [
        (1, 'Lost Miiltary Transport on', 'Lost Military Transport on'),
        (1, 'towards the Sagans Lights system, circumventing', "towards the Sagan's Lights system, circumventing"),
    ],
    'news_magellanempirefleetvisitsdourosforunknownreasons.txt': [
        (1, 'for such a manouvre could be logistical,', 'for such a manoeuvre could be logistical,'),
    ],
    'news_magellanmarugovernorcampaignheatsup.txt': [
        (1, 'sides are indiciative of the political', 'sides are indicative of the political'),
    ],
    'news_magellanmaruonlockdowntravelforbidden.txt': [
        (1, 'travel is premitted in Magellan', 'travel is permitted in Magellan'),
        (1, 'once the sitaution has been resolved,"', 'once the situation has been resolved,"'),
    ],
    'news_magellanresearchvesselsavedbypirates.txt': [
        (1, "surveying a dichromatic nebulae in De Vass'", "surveying a dichromatic nebula in De Vass'"),
    ],
    'news_magellaopenspublictransportsystem.txt': [
        (1, 'think of no beter gesture in this', 'think of no better gesture in this'),
    ],
    'news_maruthemostheavilyarmedsysteminthecluster.txt': [
        (1, 'the entire cluser.', 'the entire cluster.'),
        (1, 'this low-ley conflict might', 'this low-key conflict might'),
    ],
    'news_massiveaideffortforcansa.txt': [
        (1, 'has been magananimous, with the companies', 'has been magnanimous, with the companies'),
        (1, 'Poliical scientists,', 'Political scientists,'),
    ],
    'news_massivesandraidoncapitalfreighter.txt': [
        (1, 'its lauch window," said', 'its launch window," said'),
    ],
    'news_militarydeployedtoquellprotests.txt': [
        (1, 'deployed Gallilean Command military', 'deployed Galilean Command military'),
    ],
    'news_miningvesselsmissing.txt': [
        (1, 'upon detecing ships without', 'upon detecting ships without'),
    ],
    'news_multinationaleffortstocurbprotestsintega.txt': [
        (1, 'are being premitted entry to the', 'are being permitted entry to the'),
        (1, 'a full re-enstatement of an interstellar', 'a full reinstatement of an interstellar'),
    ],
    'news_narelaacceptsleonassistance.txt': [
        (1, 'at self-sustainance since then,', 'at self-sustenance since then,'),
    ],
    'news_nationalholidaytohonourjansky.txt': [
        (1, 'but when aksed later if he', 'but when asked later if he'),
    ],
    'news_newgrapplingarm.txt': [
        (1, 'minute of manouvres - positioning', 'minute of manoeuvres - positioning'),
    ],
    'news_newtradedealsstruckbetweengalileoandcentralsystems.txt': [
        (1, "Command's agircultural capacity.", "Command's agricultural capacity."),
    ],
    'news_newxiaosapartsselloutquickly.txt': [
        (1, 'have poppoed up for the highly', 'have popped up for the highly'),
    ],
    'news_nezhaaftdiscovered.txt': [
        (1, 'in Maru yesterdy containing many', 'in Maru yesterday containing many'),
    ],
    'news_nomorenewprisonerssaysvang.txt': [
        (1, 'Station to racuous applause today:', 'Station to raucous applause today:'),
        (1, 'people, but less to to the authorities under her command', 'people, but less to the authorities under her command'),
    ],
    'news_nospecialeconomiczonesingalileo.txt': [
        (1, 'While it is permissable for businesses', 'While it is permissible for businesses'),
    ],
    'news_nosurvivorsonjansky.txt': [
        (1, 'mortified behond belief," said', 'mortified beyond belief," said'),
    ],
    'news_notinourname.txt': [
        (1, 'want to honur the violence', 'want to honour the violence'),
    ],
    'news_notonourdoorstep.txt': [
        (1, 'ways and rejoing polite society.', 'ways and rejoin polite society.'),
    ],
    'news_okpikchangescorporatelaw.txt': [
        (1, 'by many as desiged to curtail the', 'by many as designed to curtail the'),
    ],
    'news_omegacomesoutinsupportofbednarski.txt': [
        (1, 'for General Secreatary Felicia Bednarski', 'for General Secretary Felicia Bednarski'),
    ],
    'news_outagescauseconcern.txt': [
        (1, "Konig echod Senator Bergeron's", "Konig echoed Senator Bergeron's"),
    ],
    'news_outcryagainstlivesexdolls.txt': [
        (1, 'recent exposive reports that', 'recent explosive reports that'),
        (1, 'is utterly apalling, these are human', 'is utterly appalling, these are human'),
        (1, 'able to do waht we want with', 'able to do what we want with'),
    ],
    'news_paidprotesterssowedapathyatsterling.txt': [
        (1, 'for comapnies under the law', 'for companies under the law'),
    ],
    'news_panicoverradiationleaksonrossi.txt': [
        (1, 'drop in fertiliy rates due to', 'drop in fertility rates due to'),
    ],
    'news_paramilitaryactivityoncrassus.txt': [
        (1, 'operate un-impuned on Leon soil?', 'operate un-impugned on Leon soil?'),
    ],
    'news_parssusstandsalone.txt': [
        (1, 'of an old instutition or any other', 'of an old institution or any other'),
    ],
    'news_perfectgetaway.txt': [
        (1, 'noses of a dozens of patrol ships. So much for', 'noses of dozens of patrol ships. So much for'),
    ],
    'news_presidentgonzalezapologiesformagellankilling.txt': [
        (1, 'a joint satement at a press conference', 'a joint statement at a press conference'),
    ],
    'news_protestscontinueinspiteofgonzalezoffer.txt': [
        (1, 'about an intiative HE', 'about an initiative HE'),
        (1, 'HE caleld for to begin', 'HE called for to begin'),
        (1, 'to just kil it entirely,', 'to just kill it entirely,'),
        (1, "that he thinkg we don't know", "that he think we don't know"),
    ],
    'news_protestseruptoverinterstellartrade.txt': [
        (1, "Placards saing 'solitary, sovereign,", "Placards saying 'solitary, sovereign,"),
    ],
    'news_proudgoesontheoffensive.txt': [
        (1, 'Sarni, it seemsl ike the system', 'Sarni, it seems like the system'),
        (1, 'Inerviewer: "So you\'d suggest', 'Interviewer: "So you\'d suggest'),
    ],
    'news_proudstacticsasoldastimeitself.txt': [
        (1, 'event preceeded these measures.', 'event preceded these measures.'),
    ],
    'news_radiationtoblameforrossiinfertilitycrisis.txt': [
        (2, 'for Rossi Infertiliy Crisis?', 'for Rossi Infertility Crisis?'),
        (1, 'reports of infertiliy on the moon', 'reports of infertility on the moon'),
        (1, 'to strike fertiliy system before', 'to strike fertility system before'),
    ],
    'news_recountcalledinmagellanmaruelection.txt': [
        (1, '54 votes, promting calls from the', '54 votes, prompting calls from the'),
    ],
    'news_reviewcommunalchildrearingahistory.txt': [
        (1, 'by parents who no are no longer forced to attach', 'by parents who are no longer forced to attach'),
    ],
    'news_rightwinggroupattacksrefugeehousing.txt': [
        (1, 'running rampat among the recent', 'running rampant among the recent'),
        (1, 'two were hospialised.', 'two were hospitalised.'),
    ],
    'news_rutternotintegasborderssaysgovernment.txt': [
        (1, 'Tegan space if you measures from the nearest', 'Tegan space if you measure from the nearest'),
        (1, 'The govenrment will instead', 'The government will instead'),
    ],
    'news_sabotageoncrawfordindustrial.txt': [
        (1, 'metallic errosion of an unknown', 'metallic erosion of an unknown'),
    ],
    'news_saganresearchwashesoutthecompetition.txt': [
        (1, "the Ruan Governer's office. 'Sagan", "the Ruan Governor's office. 'Sagan"),
    ],
    'news_sandbustmakingwaves.txt': [
        (1, 'outlawed, people can turned overnight from entrepreneurs', 'outlawed, people can turn overnight from entrepreneurs'),
    ],
    'news_sandoulawedinsaganslights.txt': [
        (1, 'has been undgoing significant', 'has been undergoing significant'),
    ],
    'news_sandoutlawedthroughouthtemagellanempire.txt': [
        (1, 'over, taining our Empire with', 'over, tainting our Empire with'),
    ],
    'news_sarniagriculturaldeemedlegallysellable.txt': [
        (1, 'Sarni Agircultural is legal under', 'Sarni Agricultural is legal under'),
    ],
    'news_sarnitotakemorerecansans.txt': [
        (1, "refugees, arguiung that the colony's", "refugees, arguing that the colony's"),
    ],
    'news_securityconcernsindiwalineseprisons.txt': [
        (1, 'dissent have begin to engulf the prison guard', 'dissent have begun to engulf the prison guard'),
    ],
    'news_sendhimbackleonsdontwantokpik.txt': [
        (1, 'Crassus in returement for the rest', 'Crassus in retirement for the rest'),
    ],
    'news_severaldeadinmininaccidentonmurrindal.txt': [
        (1, 'been avoidd," said Union', 'been avoided," said Union'),
    ],
    'news_shipperishesinasteroids16dead.txt': [
        (1, 'and sixteen sould have been lost', 'and sixteen souls have been lost'),
    ],
    'news_shockdevassstaropenforbusiness.txt': [
        (1, "owned by reisdents of De Vass'", "owned by residents of De Vass'"),
    ],
    'news_shockzonesforhomeless.txt': [
        (1, 'Short: Apalling Electrocution', 'Short: Appalling Electrocution'),
        (1, 'Subject: Apalling Electrocution', 'Subject: Appalling Electrocution'),
        (1, 'Derek Proud sugests this measure', 'Derek Proud suggests this measure'),
    ],
    'news_shouldauthorityvesselscarryexplosives.txt': [
        (1, '"But the deterrant of explosives', '"But the deterrent of explosives'),
    ],
    'news_shouldleonaerospaceprotectionbeapaidservice.txt': [
        (1, 'leaked, promting huge discussion', 'leaked, prompting huge discussion'),
    ],
    'news_spokespersonforlifescienceretires.txt': [
        (1, 'with my achivements," said Maki.', 'with my achievements," said Maki.'),
    ],
    'news_statementoncloning.txt': [
        (1, 'core in attendnace on at Loaiso', 'core in attendance on at Loaiso'),
    ],
    'news_stormedatmidnightcorreacollaboratorskilled.txt': [
        (1, 'in the corageous assault on these', 'in the courageous assault on these'),
    ],
    'news_strikesendingalileancommand.txt': [
        (1, 'up to his explusion from office.', 'up to his expulsion from office.'),
    ],
    'news_supportforprotestentersgalileo.txt': [
        (1, 'Short: Foostuffs and Aid Enters', 'Short: Foodstuffs and Aid Enters'),
        (1, 'Subject: Foostuffs and Aid Enters', 'Subject: Foodstuffs and Aid Enters'),
    ],
    'news_svobudracaptainwantedformurder.txt': [
        (1, "of the Parsssus People's Union", "of the Parssus People's Union"),
        (1, 'let us know that that this investigation will work together', 'let us know that this investigation will work together'),
    ],
    'news_svobudradevilintheshadows.txt': [
        (1, 'force) in enerst during the "23a', 'force) in earnest during the "23a'),
    ],
    'news_tandrirobertssonenterspoliticsasaconservative.txt': [
        (1, 'of our conversative political wing', 'of our conservative political wing'),
    ],
    'news_tegabacksbednarskiinunionfeud.txt': [
        (1, 'upon her insterstellar allies to back', 'upon her interstellar allies to back'),
    ],
    'news_tegafeelingtheleonhousingbubble.txt': [
        (1, 'crises of houseing and employment', 'crises of housing and employment'),
    ],
    'news_tegafollowsleosexamplebanssand.txt': [
        (1, 'The drug has ben misused by the wider', 'The drug has been misused by the wider'),
        (1, 'people everywhre just looking', 'people everywhere just looking'),
    ],
    'news_tegannationalbeingtriedforespionage.txt': [
        (1, 'Pablo breifly mentioned to', 'Pablo briefly mentioned to'),
        (1, 'under suspiciion of espionage.', 'under suspicion of espionage.'),
    ],
    'news_teganweaponssmugglingduringrolondwar.txt': [
        (1, 'lost their postiions of power, the', 'lost their positions of power, the'),
    ],
    'news_teganworkersprotestpoorworkingconditions.txt': [
        (1, 'some of the legitimtate concerns being', 'some of the legitimate concerns being'),
    ],
    'news_temporaryonlysaysproud.txt': [
        (1, "Only', sayd Proud", "Only', said Proud"),
    ],
    'news_tjc_opedwhysofewanswersfromjansky.txt': [
        (1, 'incident as an horrific tragedy and it most', 'incident as a horrific tragedy and it most'),
    ],
    'news_totalshutdownoftraveltojansky.txt': [
        (1, 'docking permisson to any non-', 'docking permission to any non-'),
        (1, 'to any non-miltiary vessels.', 'to any non-military vessels.'),
    ],
    'news_tradersseekgreenerpastures.txt': [
        (1, 'contracts, and its clear that the market will', "contracts, and it's clear that the market will"),
    ],
    'news_traitorexiled.txt': [
        (1, 'tolerate invidivualistic tendencies like', 'tolerate individualistic tendencies like'),
    ],
    'news_traitorklegreturnstoparssus.txt': [
        (1, 'viewed with leaniency.', 'viewed with leniency.'),
    ],
    'news_twocandidatesrunningforprogressiveleadership.txt': [
        (1, 'their party thorugh the next election.', 'their party through the next election.'),
    ],
    'news_ubpcrackdownescalates.txt': [
        (1, 'The UBP continues to operates a watchlist', 'The UBP continues to operate a watchlist'),
    ],
    'news_ubpnomoresaysbednarski.txt': [
        (1, 'the agency resportedly responsible', 'the agency reportedly responsible'),
    ],
    'news_ulencefederationrejectsempirescalltokillaea.txt': [
        (1, 'that a interstellar judicial body is a necessary', 'that an interstellar judicial body is a necessary'),
    ],
    'news_ulencescientistswecansaveyourcrops.txt': [
        (1, 'alongisde CEO Te Pura', 'alongside CEO Te Pura'),
    ],
    'news_unionactivistfleestega.txt': [
        (1, 'Harrassment by authorities', 'Harassment by authorities'),
    ],
    'news_unknownguestattendsaeahearing.txt': [
        (1, 'from delgates from around', 'from delegates from around'),
        (1, 'civil war insid the Parssus', 'civil war inside the Parssus'),
    ],
    'news_vividfoundingalileanspirits.txt': [
        (1, 'Offiical notices are', 'Official notices are'),
    ],
    'news_wedontneedtheaealeoandmagella.txt': [
        (1, 'talks are stil underway in', 'talks are still underway in'),
        (1, "of Leo's tarrifs on foodstuffs", "of Leo's tariffs on foodstuffs"),
    ],
    'news_whenceearthgate.txt': [
        (1, 'of grave proprtions for all Apollonians.', 'of grave proportions for all Apollonians.'),
        (1, 'to Earth. Shoul EarthGate ever', 'to Earth. Should EarthGate ever'),
    ],
    'news_whoisisabellesutherland.txt': [
        (1, "Since the anouncement from De Vass'", "Since the announcement from De Vass'"),
        (1, 'ultimately repsonsible for the Rolond', 'ultimately responsible for the Rolond'),
    ],
    'news_whydontothersystemsdoaswellasleo.txt': [
        (1, 'from Eminenc Holdings and', 'from Eminence Holdings and'),
    ],
    'news_workersshockedatbrutalmurder.txt': [
        (1, 'shock waves through out Parsuss.', 'shock waves throughout Parssus.'),
    ],
    'news_zhudemandsfreemovementinmagellanempire.txt': [
        (1, 'owing largley to the fact', 'owing largely to the fact'),
    ],
    'onm_avelinademboemail1.txt': [
        (1, "Command's, but it's destruction was brought about", "Command's, but its destruction was brought about"),
    ],
    'owi_agnespelettier.txt': [
        (1, 'spikes and waverforms, thank you.', 'spikes and waveforms, thank you.'),
    ],
    'owi_agnespelettier2.txt': [
        (1, 'spikes and waverforms, thank you.', 'spikes and waveforms, thank you.'),
    ],
    'owi_akihasagawa.txt': [
        (1, 'of how many manouvres your specific', 'of how many manoeuvres your specific'),
    ],
    'owi_akihasagawa2.txt': [
        (1, 'of how many manouvres your specific', 'of how many manoeuvres your specific'),
    ],
    'owi_akihasagawa3.txt': [
        (1, "how many manouvres you're making,", "how many manoeuvres you're making,"),
        (1, 'belts, nebulae the the like out there right?', 'belts, nebulae and the like out there right?'),
        (1, 'for more manouvres before you run', 'for more manoeuvres before you run'),
    ],
    'owi_ayagrantemail1.txt': [
        (1, '*me* out actualy, you really', '*me* out actually, you really'),
    ],
    'owi_bimingyang3.txt': [
        (1, 'safe, yes. Alwyas safe. Safe when', 'safe, yes. Always safe. Safe when'),
        (1, 'SO many reaons! Have to think', 'SO many reasons! Have to think'),
    ],
    'owi_budemail1.txt': [
        (1, 'target the incoing torpedo and', 'target the incoming torpedo and'),
        (1, "engines to accellerate, you're making", "engines to accelerate, you're making"),
        (1, 'your major manouvres.^^The two biggest', 'your major manoeuvres.^^The two biggest'),
        (1, 'in on the scavanging game.', 'in on the scavenging game.'),
    ],
    'owi_buffalohargreaves.txt': [
        (1, 'did you messaage me like you', 'did you message me like you'),
    ],
    'owi_fernandogutierrez2.txt': [
        (1, 'but its an oppressive regime. Pietro Correa', "but it's an oppressive regime. Pietro Correa"),
    ],
    'owi_lesliegarbut2.txt': [
        (1, 'it were unaninmous! But the folks', 'it were unanimous! But the folks'),
    ],
    'owi_lesliegarbutemail1.txt': [
        (1, "with such horrigfying news.^^I'll", "with such horrifying news.^^I'll"),
        (1, 'can go be a scavanger and end up with', 'can go be a scavenger and end up with'),
    ],
    'owi_nyongalexander.txt': [
        (1, "you, I'm familar.", "you, I'm familiar."),
    ],
    'owi_nyongalexander2.txt': [
        (1, 'eyesores comopared to the understatedly', 'eyesores compared to the understatedly'),
        (1, "of sense. I'm glad your happy.", "of sense. I'm glad you're happy."),
    ],
    'owi_sansarbatu.txt': [
        (1, 'on evasive manouvres to get you into', 'on evasive manoeuvres to get you into'),
    ],
    'owi_sansarbatu2.txt': [
        (1, 'on evasive manouvres to get you into', 'on evasive manoeuvres to get you into'),
    ],
    'ows_shengxu.txt': [
        (1, 'a fellow is everybit as human as', 'a fellow is every bit as human as'),
        (1, 'we humans aquire knowledge is', 'we humans acquire knowledge is'),
        (1, 'to embelish the former as', 'to embellish the former as'),
        (1, 'nothing? Than the Magellan bureaucrat ordering military', 'nothing? Then the Magellan bureaucrat ordering military'),
        (1, 'being killed? Than the Galilean official taking money', 'being killed? Then the Galilean official taking money'),
        (1, '- and those who are tend only to attack for', '- and those who tend only to attack for'),
        (1, 'Xu, captian. My name is', 'Xu, captain. My name is'),
    ],
    'passengers.txt': [
        (1, "Here's $amonut for a speedy", "Here's $amount for a speedy"),
    ],
    'psw_drabbeyforster.txt': [
        (1, "don't take kindly you you using me without warning", "don't take kindly to you using me without warning"),
        (1, 'to avoid a psychadelic attack on a', 'to avoid a psychedelic attack on a'),
    ],
    'psw_drfrankhanzi.txt': [
        (1, 'field is psychadelic pharmacology,', 'field is psychedelic pharmacology,'),
        (1, 'about the psychadelic weapon you have', 'about the psychedelic weapon you have'),
    ],
    'rdc_freddydunning.txt': [
        (1, "tells me you're been out there a while. Your", "tells me you've been out there a while. Your"),
        (1, "but it's appparently shameful not", "but it's apparently shameful not"),
        (1, "it's any of thier business!", "it's any of their business!"),
        (1, "promise me you won't flying without basic spares!", "promise me you won't fly without basic spares!"),
    ],
    'rgm_sternman2.txt': [
        (1, 'recovery of theie logs means that', 'recovery of their logs means that'),
        (1, "lack of due dilligence on your company's", "lack of due diligence on your company's"),
    ],
    'rsd_drnicholasreiffel.txt': [
        (1, 'probes. Too imporant. You go now.', 'probes. Too important. You go now.'),
    ],
    'rsh2_barwoman2.txt': [
        (1, 'text=Calllisto, she left here', 'text=Callisto, she left here'),
    ],
    'rsh2_callistobarman.txt': [
        (2, "text=Great, thank! You've been a big help.", "text=Great, thanks! You've been a big help."),
    ],
    'rsh2_carldiaz.txt': [
        (1, "I've never actaully been off Adari.", "I've never actually been off Adari."),
    ],
    'rsh2_lilybrooke.txt': [
        (1, '20s style blunderbus - and told me', '20s style blunderbuss - and told me'),
    ],
    'rsh2_tomonobuchenemail1.txt': [
        (1, "It'll get patchd through to you", "It'll get patched through to you"),
    ],
    'rsh_changyingwu2.txt': [
        (1, "you. Try me again and and I'll crush your fucking", "you. Try me again and I'll crush your fucking"),
    ],
    'rsh_changyingwu4.txt': [
        (1, "you. Try me again and and I'll crush your fucking", "you. Try me again and I'll crush your fucking"),
    ],
    'rsh_francisbonsor.txt': [
        (1, 'insanely jealous of him an Kazuko.', 'insanely jealous of him and Kazuko.'),
    ],
    'rsh_francisbonsor4.txt': [
        (1, 'insanely jealous of him an Kazuko.', 'insanely jealous of him and Kazuko.'),
    ],
    'rsh_maheebadalemail1.txt': [
        (1, 'Cansa unable to to anything. Not that I', 'Cansa unable to do anything. Not that I'),
    ],
    'rul_liamong.txt': [
        (1, 'it had no manouvreability, so I hopped', 'it had no manoeuvrability, so I hopped'),
    ],
    'scc_amoskleinemail1.txt': [
        (1, 'We value our customers privacy above all else."^^Good', 'We value our customers\' privacy above all else."^^Good'),
    ],
    'scc_mariskahowarthemail1.txt': [
        (1, 'hold is not what you where lead to believe it is. If my', 'hold is not what you were led to believe it is. If my'),
        (1, 'probably be imposable to ever really', 'probably be impossible to ever really'),
    ],
    'scc_unknownship.txt': [
        (1, 'fooled into suppling the villains', 'fooled into supplying the villains'),
    ],
    'shm_jacqueslavoisier.txt': [
        (1, "in the cluser. And I've travelled", "in the cluster. And I've travelled"),
    ],
    'shm_sharmillasingh1.txt': [
        (2, "the Sharma. It's registration is BH-738. Find", 'the Sharma. Its registration is BH-738. Find'),
        (1, "Please. It's registration is BH-738.", 'Please. Its registration is BH-738.'),
    ],
    'sig_marchellinesmith.txt': [
        (1, 'continue talkint with. Excuse', 'continue talking with. Excuse'),
    ],
    'smj_yasminchengemail2.txt': [
        (1, 'spotted jepoardised the entire operation.^^You', 'spotted jeopardised the entire operation.^^You'),
        (1, 'subject=Servies Rendered', 'subject=Services Rendered'),
    ],
    'smp_beaconemail1.txt': [
        (1, 'have me. Everytime he yelled, I', 'have me. Every time he yelled, I'),
    ],
    'spd_spud.txt': [
        (1, "why our enviroments can't sustain", "why our environments can't sustain"),
    ],
    'ssr_marcusplait.txt': [
        (1, 'text=She is surived by a daughter.', 'text=She is survived by a daughter.'),
    ],
    'ssr_secretary.txt': [
        (1, 'variant-B lyphomas. Sounds specific,', 'variant-B lymphomas. Sounds specific,'),
    ],
    'ssr_sofialangemail3.txt': [
        (2, 'few minutes to be spend thinking of you, and', 'few minutes to be spent thinking of you, and'),
    ],
    'ssv_mariemarks.txt': [
        (1, "of course! Absoutely. I don't approve", "of course! Absolutely. I don't approve"),
        (1, "her present idiosyncracies, she's a human", "her present idiosyncrasies, she's a human"),
        (1, 'very tricky situtation for you, and', 'very tricky situation for you, and'),
    ],
    'ssv_victoriamarks.txt': [
        (1, "cloning has it's issues.", 'cloning has its issues.'),
        (1, 'seems frought with peril.', 'seems fraught with peril.'),
        (1, 'growth was accellerated so she was only', 'growth was accelerated so she was only'),
    ],
    'stk_mariacupelli.txt': [
        (1, 'I have no quarrell with you, captain,', 'I have no quarrel with you, captain,'),
    ],
    'svo_cortlanddehaas.txt': [
        (1, 'you call a wordhole. So come on', 'you call a wormhole. So come on'),
    ],
    'tah_monaalajwi1.txt': [
        (1, 'text=Just an trader. Got a boat,', 'text=Just a trader. Got a boat,'),
        (1, "Galileo, Caruther's Circle, Parssus.", "Galileo, Carruther's Circle, Parssus."),
    ],
    'tga_angelareddy.txt': [
        (1, 'but also a a savvy businessman.', 'but also a savvy businessman.'),
        (1, 'laws demadning that the bulk', 'laws demanding that the bulk'),
        (1, "I'm afriad not.", "I'm afraid not."),
    ],
    'tga_test1.txt': [
        (1, 'but also a a savvy businessman.', 'but also a savvy businessman.'),
        (1, 'laws demadning that the bulk', 'laws demanding that the bulk'),
        (1, "I'm afriad not.", "I'm afraid not."),
    ],
    'tha_maxwellkerr6.txt': [
        (1, "you half. I belive that's more", "you half. I believe that's more"),
    ],
    'tjc_avelinademboemail1.txt': [
        (1, "it.^^I've been been writing for Carruther's", "it.^^I've been writing for Carruther's"),
    ],
    'tsb_asha2.txt': [
        (1, "There's an communications array, so you can", "There's a communications array, so you can"),
    ],
    'tse_francistassell.txt': [
        (1, 'supeiority become anti-Earth,', 'superiority become anti-Earth,'),
    ],
    'tsf_barlowartosemail1.txt': [
        (1, 'has had to attent to other business.', 'has had to attend to other business.'),
    ],
    'tsf_karolzimaemail1.txt': [
        (1, 'a little btter in future.^^Karol.', 'a little better in future.^^Karol.'),
    ],
    'tsk_ramonafitzloff.txt': [
        (1, "but only if its straightforward. I don't like", "but only if it's straightforward. I don't like"),
    ],
    'ufp_henriettaarcadeemail1.txt': [
        (1, 'subject=Ingocnito Travel', 'subject=Incognito Travel'),
        (1, 'subject=Re: Ingocnito Travel', 'subject=Re: Incognito Travel'),
    ],
    'wap_lukevhan.txt': [
        (1, 'someone but a troopers in my section said it was', 'someone but a trooper in my section said it was'),
    ],
    'wap_zahkirahsterling.txt': [
        (1, 'or my wife, Ginat Naive the musician.', 'or my wife, Giant Naive the musician.'),
        (1, 'my wife, Ginat Naive the musician,', 'my wife, Giant Naive the musician,'),
    ],
    'wgs_oskarmazur.txt': [
        (1, 'we can do beter than 650.', 'we can do better than 650.'),
    ],
    'wgs_oskarmazur3.txt': [
        (1, 'This Union Miliary Pride Day will', 'This Union Military Pride Day will'),
    ],
    'wig_leonofficialsemail1.txt': [
        (2, 'subject=Congratuations are in order', 'subject=Congratulations are in order'),
    ],
    'wig_notes.txt': [
        (1, 'BMN-185 and retreive its data logs.', 'BMN-185 and retrieve its data logs.'),
    ],
    'wig_unknownemail.txt': [
        (1, 'under NO circumstnaces are you to read', 'under NO circumstances are you to read'),
    ],
    'wig_unknownemail3.txt': [
        (2, 'from=Unkonwn', 'from=Unknown'),
        (1, 'you reveal any details our our communications?', 'you reveal any details of our communications?'),
    ],
    'yrs_florianogarcia.txt': [
        (1, 'Sol was an unweildy number. Some', 'Sol was an unwieldy number. Some'),
    ],
    'yrs_jylliandirou.txt': [
        (1, 'talking it striked me just how', 'talking it struck me just how'),
    ],
}
